spring.application.name=AttendanceRegister

# === Server Config ===
server.port=8080
#1
# === MongoDB Configuration ===
spring.data.mongodb.uri=mongodb+srv://pvmohaneswar:Eswar1234@cluster0.1j352.mongodb.net/attandance?retryWrites=true&w=majority&appName=Cluster0
# Exclude DataSource auto-configuration since we're using MongoDB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration